Cargo.toml
This update development series due to dependency update re-exported in
public interface.
=> cargo: update dev version

Cargo.toml, examples/notify.rs, examples/watchdog.rs, src/daemon.rs, src/errors.rs, src/id128.rs, src/lib.rs, src/unit.rs
This adds a module for handling 128-bits IDs. See `sd-id128(3)`.
=> libsystemd: add id128

src/id128.rs
This adds an output helper for lowercase hexadecimal non-dashed format.
=> id128: add lower-hex output

Cargo.toml, src/id128.rs, src/lib.rs
This adds serialization and deserialization support for `Id128`.
=> id128: add serde support

src/errors.rs, src/lib.rs, src/logging.rs
@lucab could you please review my initial pass at adding journald logging support.
1. I only have the core logic of forwarding messages to journald in place
2. I am not able to pass journald a memfd and create a log entry. I've done a bit of research and only found some issues in `nix` with passing multiple fds, but that shouldn't matter in our case.
Close: https://github.com/lucab/libsystemd-rs/issues/32
=> logging: add support for writing to journald

src/logging.rs
Fixes #43 and enable us to use that logic in the `afterburn` repo to solve(https://github.com/coreos/afterburn/issues/395)
=> Add logic to support sending structured entries to the journald log

src/logging.rs
This adds environmental checks to tests which require journald,
skipping them if not applicable.
=> logging: conditionally run journald tests

.travis.yml, README.md
This refreshes Travis configuration and adds a job to check non-x86
architectures (arm64).
=> ci: update travis and run on arm64

Cargo.toml, src/activation.rs, src/daemon.rs, src/errors.rs, src/id128.rs, src/logging.rs
This drops `error-chain` usage in favor of `thiserror`. Due to public types change, this needs a minor  version bump.
=> errors: switch to thiserror

Cargo.toml, src/activation.rs
This tweaks FD-receiving logic to account for file descriptors of an
unknown type (possibly invalid, too).
Previously this library would just halt and catch fire upon encountering
a single FD for which type-detection failed It now logs a warning message
but keeps the FD internally in a dedicated "unknown" variant, allowing
consumers to recover it and further try to process in some way.
Closes: https://github.com/lucab/libsystemd-rs/issues/46
=> activation: do not discard unknown descriptors

src/logging.rs
Priority is a trivial type to copy, so allow it for convenience.
=> logging: Derive Copy & Clone for Priority

src/logging.rs
Sending a file descriptor through a socket effectively duplicates the
file descriptor; it does not move the file descriptor out of the current
process.
Hence we need to close our side of the file descriptor explicitly to
avoid leaking file descriptors.
=> Close our side of memfd

src/sysusers/mod.rs, src/sysusers/serialization.rs
This adds support for serializing and deserializing sysusers
entries, preserving the content of each field separately.
=> sysusers: add serialization support

src/sysusers/mod.rs, src/sysusers/serialization.rs
This exposes the value for the most interesting fields of each
entry, through mildly smart getter methods.
It is meant to let consumers inspect entries without getting lost
in the details of the configuration format.
=> sysusers: expose more field details

Cargo.toml, src/errors.rs, src/logging.rs, src/sysusers/mod.rs, src/sysusers/parse.rs, src/sysusers/serialization.rs
This adds support for parsing entries from sysusers.d lines.
Overall logic is organized around the 'nom' parser-combinator
framework.
It is now possible to roundtrip configuration entries, loading
content from files as well as writing back data.
=> sysusers: add parsing logic

src/activation.rs
See https://github.com/lucab/libsystemd-rs/issues/107.
This should be compatible with existing code as well, as it just does what `nix` used to do.  I don't see any way to check a FD in this way without unsafe, unfortunately!
=> activation: fix build for compatibility with nix 0.24

examples/id128.rs, src/id128.rs
Additionally add an example for the new and existing id128::get_*
functions.
=> id128: add get_boot() and get_boot_app_specific()

src/logging.rs
This tweaks the conditional checks in `connected_to_journal()` logic, in order to avoid buggy cases.
In particular, in case of errors we may have ended up comparing `None` values possibly coming from the two sides (env and stdout/stderr stat), thus returning a false positive to consumers.
Let's instead change the logic to be more explicit in case of real positive results, and use a single fallback for all negative cases.
=> logging: fix `connected_to_journal` logic

Cargo.toml, examples/persistent_state.rs, src/daemon.rs, tests/persistent_state.rs
This is required for proper use of FDSTORE.
There's also a small example which uses FDSTORE to maintain some state which are persistent over restarts of various kinds.
=> Add support for sending file descriptors

Cargo.toml, src/credentials.rs, src/lib.rs
See https://github.com/lucab/libsystemd-rs/pull/98 for the original code/discussion behind this.
=> credentials: add helpers for accessing credential data

src/logging.rs
This changes `connected_to_journal()` behavior to only check stderr
against `$JOURNAL_STREAM` for protocol upgrading.
Protocol upgrading assumes that all the logging happens on stderr.
For that purpose, it is not relevant whether stdout is connected
to journal.
=> logging: only check stderr for protocol upgrading 

src/logging.rs
This hides `JournalStream::parse()` and `JournalStream::from_env_impl()` from the public API, as they are internal implementations and not supposed to be useful to consumers.
=> logging: unexport some JournalStream methods

src/daemon.rs, src/lib.rs
This is a draft PR for add support for unix socket abstract namespace.
Wating feature `unix_socket_abstract` stable.
Tracking issues: https://github.com/rust-lang/rust/issues/85410
=> daemon/notify: add support for abstract unix sockets

src/daemon.rs
This performs some basic sanity checks against notify-state entries.
Notably, it checks lenght and content of `FDNAME` labels.
Closes: https://github.com/lucab/libsystemd-rs/issues/116
=> daemon/notify: sanity check state entries

src/logging.rs
This removes the `to_string()` call on Priority by adding a private member function `numeric_level()`.  I've implemented the `numeric_level()` as a private member function to avoid adding to the API surface of Priority.  The provided test ensures that the function used internally and the representation publicly, via From<u8>, match.  Since rust does not have a small string optimization, this avoids an allocation for each call to `journal_send`.
This also adds a reserve call prior to adding data to the vector to avoid multiple allocations when extend and push are called, since the length of the data being added is fully known.
=> logging: reduce the amount of allocations in hotpath

Cargo.toml
Changes:
* activation: fix build for compatibility with newer `nix` 
* cargo: bump MSRV to 1.56
* ci: update workflow
* credentials: add helpers for accessing credential data
* daemon/notify: add support for abstract Unix sockets
* daemon/notify: add support for sending file descriptors
* daemon/notify: sanity check state entries
* errors: add internal helpers to simplify error handling
* id128: add `get_boot()` and `get_boot_app_specific()`
* logging: use std API to extract journal stream from FD
* logging: fix `connected_to_journal` logic
* logging: only check stderr for protocol upgrading 
* logging: reduce the amount of allocations in hotpath
* logging: un-export some JournalStream methods
Closes: https://github.com/lucab/libsystemd-rs/issues/124
=> Release 0.6.0

src/credentials.rs
This builds off of the `Context` trait introduced in #128, and implements it for the credentials module.  Everything else is a direct translation of the existing error message.
=> credentials: use internal Context helper to simplify error handling

src/id128.rs
This builds off of the `Context` trait introduced in #128, and implements it for the id128 module.  Everything is a direct translation of the existing error message.
=> id128: use internal Context helper to simplify error handling

src/sysusers/mod.rs
This builds off of the Context trait introduced in #128, and implements it for the sysusers module. This changes one value, which pulls in the original error message instead of ignoring it, and adds additional context on a second parse.  Let me know if you'd rather the error message for the parsing still be ignored.
=> sysusers: internal Context helper to simplify error handling

.github/workflows/rust.yml, Cargo.toml
This is required by our transitive dependencies (currently `regex-v1.10.2`).
=> cargo: update MSRV to 1.65

Cargo.toml
Changes:
* build(deps): update nix requirement from ^0.26 to ^0.27
* cargo: update MSRV to 1.65
* logging: fix build in armv7
* logging: directly use memfd_create syscall
* lib: fix IO safety
* feat: Enhancing Id128 structure
* logging: fix typo in connected_to_journal docs
* logging: forgo validation of MESSAGE and PRIORITY fields at runtime
* sysusers: internal Context helper to simplify error handling
* id128: use internal Context helper to simplify error handling
* daemon: use internal Context helper to simplify error handling
* credentials: use internal Context helper to simplify error handling
* activation: use internal Context helper to simplify error handling
Closes: https://github.com/lucab/libsystemd-rs/issues/147
=> cargo: libsystemd release 0.7.0

src/activation.rs
This tweaks the file descriptor logic in order to avoid spurious errors when there is a `$LISTEN_PID` mismatch, or when the variables are unset.
Closes #155
=> activation: keep going on PID mismatch

Cargo.toml
Changes:
* activation: keep going on PID mismatch
* cargo: update rand requirement from ^0.8 to ^0.9
* cargo: update nom requirement from 7 to 8
* cargo: update thiserror requirement from ^1.0 to ^2.0
* cargo: update nix requirement from ^0.27 to ^0.28
* ci: use MSRV from cargo manifest
=> cargo: libsystemd release 0.7.1

src/activation.rs
The systemd function sd_listen_fds sets the FD_CLOEXEC flag on file descriptors that are passed in via socket activation, so that they aren't accidentally propagated to child processes forked/exec'd from your daemon.  We should do that too.
=> activation: Set FD_CLOEXEC on the fds we receive.

examples/persistent_state.rs, src/logging.rs, src/sysusers/parse.rs, tests/journal.rs, tests/persistent_state.rs
- Remove a stray doc comment.
- Match a pattern rather than using `if x == y`.
- Explicitly truncate newly-created files in tests/examples.
- Remove an unnecessary & in a test.
---
Some minor things I noticed and decided to eliminate in the name of getting rid of squiggly underlines and probably code health too I guess.
=> cleanup: fix some Clippy warnings.
