- .travis.yml
This updates clippy version and check minimum toolchain version.
> travis: update clippy and check minimum version

- .travis.yml
- src/id128.rs
This bumps minimum toolchain to 1.31.
> travis: bump toolchains

- src/id128.rs
This adds a fallible constructor to build an `Id128` from a bytes-slice.
> id128: add a bytes constructor

- Cargo.toml
* unit: add escape helpers
* id128: add 128-bits IDs
* cargo: update all dependencies
> cargo: libsystemd release 0.1.0

- src/id128.rs
This adds a Clone implementation for Id128.
> id128: derive Clone

- .travis.yml
- Cargo.toml
- src/daemon.rs
- src/lib.rs
- src/unit.rs
> Drop try_or dependency

- src/activation.rs
- src/lib.rs
This fixes a few typos and minor things, plus it polishes the public
API.
> activation: polish code and misc fixes

- src/lib.rs
- src/logging.rs
This re-arranges the logic and polishes a few minor internal details
in logging module.
> logging: misc rework and polish

- src/daemon.rs
This is just a random drive-by change while figuring out if I can use this crate in a project.
> Optimize NotifyState

- .travis.yml
- Cargo.toml
- src/errors.rs
- src/unit.rs
This contains several CI and projects cleanups, plus a minimum toolchain bump.
> libsystemd: misc CI and project cleanups

- Cargo.toml
Changes:
* cargo: switch to edition 2018
* logging: add support for writing to journald
* logging: add logic to support sending structured entries to journald
* misc CI and project cleanups
* daemon: optimize NotifyState
* activation: add sd_listen_fds and sd_listen_fds_with_names
* docs: add licenses and copyrights
* id128: derive Clone
> Release 0.2.0

- src/activation.rs
This tweaks the socket activation logic to propagate errors
whenever FD reception fails.
Ref: https://github.com/lucab/libsystemd-rs/issues/46
> activation: return errors on FD reception errors

- Cargo.toml
Changes:
* activation: return errors on FD reception failures
* ci: update travis and run on arm64
* logging: conditionally run journald tests
> Release 0.2.1

- .github/workflows/rust.yml
- src/activation.rs
This updates CI toolchains and fixes all new clippy warnings.
> ci: bump toolchains

- Cargo.toml
- src/logging.rs
- tests/journal.rs
> Properly encode multiline journal messages

- Cargo.toml
Changes:
* activation: do not discard unknown descriptors
* errors: switch to thiserror
* logging: properly encode multiline journal messages
* cargo: refresh all dependencies
* ci: upgrade to GitHub-native Dependabot
* ci: bump toolchains
* ci: move Travis jobs to GitHub actions
> Release 0.3.0

- src/logging.rs
systemd requires journal fields to be ASCII only and has some additional restrictions, see [`journal_field_valid` in `systemd/journal_file.c`](https://github.com/systemd/systemd/blob/ed056c560b47f84a0aa0289151f4ec91f786d24a/src/libsystemd/sd-journal/journal-file.c#L1557)
> Fix checks for invalid journal fields

- Cargo.toml
> Happy to help 

- Cargo.toml
- src/logging.rs
- tests/journal.rs
> Reuse socket

- src/lib.rs
- src/sysusers/format.rs
- src/sysusers/mod.rs
This adds the initial datastructures and logic to handle configuration
entries in 'sysusers.d' format.
Ref: https://www.freedesktop.org/software/systemd/man/sysusers.d.html
> sysusers: introduce new module for 'sysusers.d' configuration

- Cargo.toml
- src/id128.rs
> cargo: update sha2 and hmac to new version

- .github/workflows/rust.yml
- src/logging.rs
> Use std API to extract journal stream from fd

- src/activation.rs
This builds off of the `Context` trait introduced in #128, and implements it for the activation module.  There was one additional Try/? to which I added context; everything else is a direct translation of the existing error message.
> activation: use internal Context helper to simplify error handling

- src/daemon.rs
This builds off of the `Context` trait introduced in #128, and implements it for the daemon module.  Everything is a direct translation of the existing error message.
> daemon: use internal Context helper to simplify error handling

- src/logging.rs
This changes where the validation of the field happens to so that the validity of MESSAGE and PRIORITY can be asserted during tests, rather than in each run of add_field_and_payload.
To make this a little more explicit, this changes introduces ValidField as a helper struct for the interface on add_field_and_payload. ValidField is constructed primarily by calling it's `validate` function, which returns None if the field is invalid.  It also has an `unchecked` function that effectively breaks this guarantee, under the assumption that `validate_unchecked` will be called during tests.  This pair allows for ValidField to be `const`.
> Forgo validation of MESSAGE and PRIORITY fields at runtime

- src/logging.rs
memfd is only available starting with Linux 3.17 and glibc 2.27. In old systems, this may not be available.
To support usage in these old systems, this adds a feature flag "memfd" that makes using "memfd" optional. The feature flag is included in the default features, so this does not change the default behaviour.
When the crate is built without the memfd feature flag, the journal_send function will return an error if the message does not fit in a UNIX socket, instead of trying to use memfd to send the message.
---
As a rationale for this, I'm running on an old ARMv7 system that doesn't have memfd. In fact, I'm cross-compiling with [cross](https://github.com/cross-rs/cross), which is a popular way of cross-compiling Rust crates. When building for armv7-unknown-linux-gnueabihf, the current …
> add feature flag to allow disabling use of memfd

- src/logging.rs
In armv7-unknown-linux-gnueabihf (ARM 32-bit), `FileStat::inode` is an `u32` instead of an `u64`, so we need to convert it to `u64`.
> logging: fix build in armv7
